name: Create a comment on new issues


on: 
  issues:
    types: [opened] #run whenever we create a issue


jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps: # create commant on that particualr issue
      - name: "dumpe github context"  #Need ISSUE Id FOR CREATE FOR RTHAT COMMENT
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: '${{ github.event.issue.number }}'
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'



